//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> IdTV { get; set; }
        public Nullable<int> IdSP { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual Product Product { get; set; }
    }
}
