//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BillInfoes = new HashSet<BillInfo>();
            this.BillNhapInfoes = new HashSet<BillNhapInfo>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Info { get; set; }
        public string Image { get; set; }
        public string Inventory { get; set; }
        public string Overview { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> Comment { get; set; }
        public Nullable<int> IdNCC { get; set; }
        public Nullable<int> IdNSX { get; set; }
        public Nullable<int> IdLSP { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> New { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public Nullable<int> NhomSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillNhapInfo> BillNhapInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual NhomSanPham NhomSanPham { get; set; }
    }
}
